-------------------------------------------------------------------------------
-- D. CAN YOU PROVIDE A LIST WITH CUSTOMERS_IDS WHO HAD ONLY OPEN OR OVERDUE CYCLES? (HINT:
-- CHECK UNIQUE VALUES OF CYCLES STATUS COLUMN)
 
SELECT CUSTOMER_ID
FROM CYCLES
GROUP BY CUSTOMER_ID
HAVING COUNT(*) = SUM(CASE WHEN STATUS IN ('open','overdue') THEN 1 ELSE 0 END)

