-------------------------------------------------------------------------------
-- C. CAN YOU PROVIDE THE CUSTOMER_ID OF ALL CUSTOMERS THAT HAD MORE THAN 1 APPLICATION WITHIN A TIME PERIOD OF 30 DAYS?

WITH QRY1 AS (
SELECT CUSTOMER_ID,
	COUNT(ID) AS CNT
FROM APPLICATIONS
WHERE CUSTOMER_ID IS NOT NULL
GROUP BY CUSTOMER_ID
HAVING COUNT(ID) > 1
)

SELECT A.CUSTOMER_ID
FROM APPLICATIONS AS A 
INNER JOIN APPLICATIONS AS B ON (A.CUSTOMER_ID = B.CUSTOMER_ID AND A.CREATED_AT <> B.CREATED_AT)
WHERE ABS(DATE_PART('DAY',A.CREATED_AT-B.CREATED_AT)) < 30
AND A.CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM QRY1)
GROUP BY A.CUSTOMER_ID
