-------------------------------------------------------------------------------
-- E. CAN YOU PROVIDE AN ORDERED LIST OF CUSTOMERS OVER THEIR PERCENTAGE OF OVERDUE CYCLES
-- PER CUSTOMER?

SELECT CUSTOMER_ID,
(SUM(CASE WHEN STATUS IN ('overdue') THEN 1 ELSE 0 END)::FLOAT / COUNT(ID)::FLOAT)*100  AS OVERDUE_PERC
FROM CYCLES
GROUP BY CUSTOMER_ID
ORDER BY OVERDUE_PERC DESC
