
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DROP TABLE IF EXISTS CUSTOMER_EMAIL;

CREATE TABLE CUSTOMER_EMAIL AS 
WITH CUSTOMER_MASTER AS 
(SELECT 
 CUSTOMER_ID,
 EMAIL,
 CASE WHEN RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY ID DESC) = 1 THEN 1 ELSE 0 END AS IS_ACTIVE 
 FROM APPLICATIONS
WHERE CUSTOMER_ID IS NOT NULL),

TASK_5 as 
(SELECT CYC.CUSTOMER_ID, CMR.EMAIL
FROM CYCLES CYC
LEFT JOIN CUSTOMER_MASTER CMR ON (CYC.CUSTOMER_ID = CMR.CUSTOMER_ID and CMR.IS_ACTIVE = 1)
GROUP BY CYC.CUSTOMER_ID,CMR.EMAIL
HAVING MAX(CYC.DPD) > 10)

select 
CUSTOMER_ID,
pgp_pub_encrypt (email,dearmor ( '{}' )) as encrypted_email
from task_5;


